services:
  acc:
    image: MailingAccBot:latest
    command: ["sh", "/app/run.sh"]
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - mysql
    restart: unless-stopped
    tty: true

  mysql:
    image: mysql:8.0.33
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /var/log/mysql
      - /var/lib/mysql
    tty: true